cmake: toolchain: Add support to build with LLVM-embedded-toolchain-for-Arm
- Pass correct flags to Clang to make sure object files link
with -lc, -lm, and -lclang_rt.builtins libraries.

- Set LLVM_LINK_LIB to link -lc -lm -lclang_rt.builtins librares
  required by ld.lld. It solves the following error.
  -- snip --
  ld.lld: error: unable to find library -lc
  ld.lld: error: unable to find library -lm
  ld.lld: error: unable to find library -lclang_rt.builtins
  clang-16: error: ld.lld command failed with exit code 1 (use -v to see
  invocation)
  -- snip --

- Use LLVM built-in linker (ld.lld) as a default linker through
  LLVM_USE_LLD. The ld.bfd linker gives the following error.
  -- snip --
  /usr/bin/ld.bfd: unrecognized option '--target2=rel'
  /usr/bin/ld.bfd: use the --help option for usage information
  clang: error: ld.lld command failed with exit code 1
  (use -v to see invocation)
  -- snip --

- Avoid passing unrecognised option '--specs=nosys.specs' for lld linker.
  -- snip --
  clang: warning: argument unused during compilation: '--specs=nosys.specs'
  [-Wunused-command-line-argument]
  -- snip --

- The libgcc.a is unavailable with LLVM-embedded-toolchain-for-Arm,
  so avoid passing with lld linker.
  -- snip --
  ld.lld: error: unable to find library -lgcc
  clang: error: ld.lld command failed with exit code 1
  (use -v to see invocation)
  -- snip --

- Select BUILD_NO_GAP_FILL to solve the following error.
  -- snip --
  ../LLVMEmbeddedToolchainForArm-17.0.1-Linux-x86_64/bin/llvm-objcopy:
  error: unknown argument '--gap-fill'
  -- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jagadeesh@alifsemi.com>