cmake: toolchain: Add support to build with armclang
- armlink: fix to compile applications for MRAM.
Any zephyr application fails to build with the below error
when configured to boot from MRAM (0x80000000).
  -- snip --
  [ 91%] Linking C executable zephyr_pre0.elf
  Error: L6384E: No Load Execution Region of name bss seen yet at line 11.
  Error: L6384E: No Load Execution Region of name bss seen yet at line 15.
  Not enough information to list the image map.
  Finished: 1 information, 0 warning and 2 error messages.
  rtss_hp/zephyr/CMakeFiles/zephyr_pre0.dir/build.make:162: recipe for
target 'rtss_hp/zephyr/zephyr_pre0.elf' failed
  make[2]: *** [rtss_hp/zephyr/zephyr_pre0.elf] Error 1
  make[2]: Leaving directory '.../zephyr/build'
  CMakeFiles/Makefile2:2934: recipe for target
  'rtss_hp/zephyr/CMakeFiles/zephyr_pre0.dir/all' failed
  make[1]: *** [rtss_hp/zephyr/CMakeFiles/zephyr_pre0.dir/all] Error 2
  make[1]: Leaving directory '.../zephyr/build'
  Makefile:90: recipe for target 'all' failed
  make: *** [all] Error 2
  -- snip --

  This is due to misplacing of .bss macros in the IDT_LIST
  section instead of the FLASH section. The misplacing of the
  macros happens when the FLASH_BASE_ADDRESS is more than the
  SRAM_BASE_ADDRESS as the linker_script_common.cmake script
  sorts parameters lexicographically.

  To solve the above error make sure parameters are not sorted
  when the FLASH_BASE_ADDRESS is more than the SRAM_BASE_ADDRESS
  while using armclang toolchain.

- Increase IDT_LIST to 4K same as used with GCC to solve
below error while building samples/drivers/ipm/ipm_alif_hwsem.
  -- snip --
  Error: L6220E: Load region IDT_LIST size (2328 bytes) exceeds
  limit (2048 bytes). Region contains 0 bytes of padding and
  0 bytes of veneers (total 0 bytes of linker generated content).
  Finished: 0 information, 0 warning and 1 error messages.
  zephyr/CMakeFiles/zephyr_pre0.dir/build.make:170:
  recipe for target 'zephyr/zephyr_pre0.elf' failed
  make[2]: *** [zephyr/zephyr_pre0.elf] Error 1
  CMakeFiles/Makefile2:2919: recipe for target
  'zephyr/CMakeFiles/zephyr_pre0.dir/all' failed
  make[1]: *** [zephyr/CMakeFiles/zephyr_pre0.dir/all] Error 2
  Makefile:90: recipe for target 'all' failed
  -- snip --

- Workaround to huge bin file when compiling with armclang.
When compiling display application with armclang, observing
huge bin file. The issue is a toolchain issue and no issue
observed with GCC compiler. Providing a workaround to take
hard-coded FB address rather than allocating the required FBs
on the fly.

Signed-off-by: Jagadeesh Krishnanjanappa <jagadeesh@alifsemi.com>